### ISSUE TITLE
Feature request : isInvertible

### ISSUE THREAD

**Issue by piercus** [metabolize/matrix-inverse#10]
Hello,

Thanks for this library, very useful ! I've just published https://github.com/piercus/kalman-filter which is using matrix-inverse.

Would it be possible to include a function like isInvertible(matrix) to know if the matrix is invertible.
It will give the ability to check before the code is crashing !

Use case

## Actual
```js
const matrixInverse = require('matrix-inverse');
matrixInverse([[0,0],[0,0]]) // Cannot read property 'elements' of null
```

## Expected
(just a proposal)
```js
const matrixInverse = require('matrix-inverse');
const mat = [[0,0],[0,0]];
let invert;
if(matrixInverse.isInvertible(mat)){
  invert = matrixInverse(mat); // Cannot read property 'elements' of null
} else {
  console.log('matrix is not invertible');
  invert = null;
}
```

Thanks for your help

**Comment by paulmelnikow** [comment]
Hi! As an alternative, perhaps instead of crashing it could return `undefined` when a matrix isn't invertible.

Sure! A pull request would be welcome!

**Comment by piercus** [comment]
Yes, it might be better.

I'm only afraid it could break existing code if someone has already made a try/catch mechanism ! 

Are you ok with this ? Please confirm

**Comment by paulmelnikow** [comment]
Yes, I think throwing an error on an uninvertible matrix is a bug. Though we could ship the change in a major release, as a breaking change, just in case downstream users depend on that behavior.

**Comment by paulmelnikow** [comment]
Thanks for the PR!
